-- CreateTable
CREATE TABLE `BCLoads` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `envType` INTEGER UNSIGNED NOT NULL,
    `loadType` INTEGER UNSIGNED NOT NULL,
    `lastBlockNumber` VARCHAR(63) NOT NULL,
    `beginAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `endAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
