-- CreateTable
CREATE TABLE `BCMonsters` (
    `monsterId` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `name` VARCHAR(63) NOT NULL,
    `supplyLimit` INTEGER UNSIGNED NOT NULL,
    `SupplyCount` INTEGER UNSIGNED NOT NULL,
    `updatedAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`monsterId`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `BlockChainMints` (
    `id` INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
    `tokenId` INTEGER UNSIGNED NOT NULL,
    `monsterId` INTEGER UNSIGNED NOT NULL,
    `createdAt` TIMESTAMP(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),

    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
