import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const styles = {
  nav: {
    backgroundColor: "#f8f9fa",
    padding: "1rem",
    boxShadow: "0 2px 4px rgba(0,0,0,0.1)"
  },
  navList: {
    listStyle: "none",
    display: "flex",
    gap: "1rem",
    margin: 0,
    padding: 0,
    justifyContent: "center"
  },
  navLink: {
    color: "#0070f3",
    textDecoration: "none",
    fontWeight: 500,
    transition: "color 0.3s ease"
  }
} as const;

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <head>
        <title>Next Eggrypto Debug</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav style={styles.nav}>
          <ul style={styles.navList}>
            <li><Link href="/" style={styles.navLink}>Top</Link></li>
            <li><Link href="/blockchainmint" style={styles.navLink}>CreationEvents</Link></li>
            <li><Link href="/blockchainmonster" style={styles.navLink}>MonsterSupplys</Link></li>
          </ul>
        </nav>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}


