import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import React from "react";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: Props) {
  return (
    <html lang="en">
      <head>
        <title>Next Eggrypto Debug</title>
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav>
          <ul style={{ listStyle: "none", display: "flex", gap: "1rem" }}>
            <li><Link href="/">Home</Link></li>
            <li><Link href="/blockchainmonster">BlockChainMonster</Link></li>
            <li><Link href="/blockchainmint">BlockChainMint</Link></li>
          </ul>
        </nav>
        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
