name: Scheduled API Request

on:
  schedule:
    - cron: '30 * * * *'

jobs:
  curl_job:
    runs-on: ubuntu-latest
    steps:
      - name: Send HTTP Request
        run: curl -X GET 'https://next-eggrypto-debug-production.up.railway.app/api/createMonsterEvent/fetch?limit=100'
